# Generated by Django 3.0.7 on 2020-06-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_cover', verbose_name='Обложка книги')),
                ('price', models.FloatField(verbose_name='Стоимость книги')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genre.Genre')),
            ],
        ),
    ]
