# Generated by Django 3.0.7 on 2020-07-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('image', models.ImageField(null=True, upload_to='book_cover', verbose_name='Обложка книги')),
                ('price', models.FloatField(verbose_name='Стоимость книги')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('quantity', models.IntegerField(verbose_name='Количество страниц')),
                ('binding', models.CharField(max_length=100, verbose_name='Переплет')),
                ('forma', models.CharField(max_length=10, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Вес (гр.)')),
                ('age', models.IntegerField(verbose_name='Возрастные ограничения')),
                ('publishing', models.CharField(max_length=20, verbose_name='Издательство')),
                ('rate', models.IntegerField(verbose_name='Рейтинг (0-10)')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ManyToManyField(max_length=100, to='author.Author', verbose_name='Автор книги')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genre.Genre')),
            ],
        ),
    ]
