# Generated by Django 3.0.7 on 2020-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('books', '0002_auto_20200713_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books', to='author.Author', verbose_name='Автор'),
        ),
    ]
