# Generated by Django 3.0.7 on 2020-06-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='add_date',
            new_name='add_time',
        ),
    ]
