# Generated by Django 3.0.7 on 2020-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('books', '0003_auto_20200713_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='genre.Genre', verbose_name='Жанр'),
        ),
    ]
