# Generated by Django 3.0.7 on 2020-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('books', '0005_auto_20200713_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='books1', to='genre.Genre', verbose_name='Жанр'),
        ),
    ]
