# Generated by Django 3.0.7 on 2020-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('books', '0006_auto_20200713_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='genre.Genre', verbose_name='Жанр'),
        ),
    ]
