# Generated by Django 3.0.6 on 2020-06-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parsing_string',
        ),
        migrations.AddField(
            model_name='parsing_date',
            name='string',
            field=models.TextField(blank=True, null=True, verbose_name='String'),
        ),
    ]
