# Generated by Django 3.0.6 on 2020-06-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='testapp.Genre', verbose_name='Жанр книги'),
            preserve_default=False,
        ),
    ]
