# Generated by Django 3.0.6 on 2020-06-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
