# Generated by Django 3.0.6 on 2020-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200604_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('browser', models.CharField(blank=True, max_length=10, null=True, verbose_name='Browser')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Parsing_browser',
        ),
        migrations.DeleteModel(
            name='Parsing_date',
        ),
        migrations.DeleteModel(
            name='Parsing_ip',
        ),
    ]
