# Generated by Django 3.0.7 on 2020-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1, max_length=15, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
