# Generated by Django 3.0.7 on 2020-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200707_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(default=1, max_length=500, verbose_name='Адрес доставки основной'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки дополнительный'),
        ),
    ]
