# Generated by Django 3.0.7 on 2020-07-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('profiles', '0004_mygroups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyGroups',
        ),
    ]
