# Generated by Django 3.0.7 on 2020-07-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200713_1546'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_in_cart', to='books.Books', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='cart.Cart'),
        ),
    ]
